apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfigmap
data:
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_HOST: "localhost"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: mypassword